//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeStory.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubjectCross
    {
        public int Id { get; set; }
        public int IdStudent { get; set; }
        public string CodeSubject { get; set; }
        public string NameSubject { get; set; }
        public int Credits { get; set; }
        public int Semester { get; set; }
        public string GradeLetter { get; set; }
        public Nullable<double> GradeNumber { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
